Repository short-d/kgs, pull requests merged in 2020-01, with the labels that each got.

#44 Update app framework to latest version
  app/app.go
  app/usecase/keys/consumer_test.go
  go.mod
  go.sum
Labels: size/S

#45 Refactor the business logics into use case
  app/adapter/message/message.go
  app/adapter/rpc/kgs.go
  app/adapter/template/data.go
  app/adapter/template/keygensucceed.go
  app/app.go
  app/usecase/usecase.go
  dep/provider/template.go
  dep/wire.go
  dep/wire_gen.go
  go.sum
  main.go
Labels: size/L

#52 Experimental event dispatcher integration
  app/usecase/event/dispatcher.go
  app/usecase/event/dispatcher_test.go
  app/usecase/event/interface.go
  go.mod
  go.sum
Labels: enhancement

#54 App dispatcher
  app/app.go
  app/usecase/dispatcher/emitter.go
  app/usecase/event/dispatcher.go
  app/usecase/event/dispatcher_test.go
  app/usecase/event/interface.go
  app/usecase/notification/email.go
  app/usecase/notification/event.go
  app/usecase/notification/listener.go
  app/usecase/notification/listener_test.go
  app/usecase/notification/notifier.go
  app/usecase/usecase.go
  cmd/cmd.go
  dep/provider/notifier.go
  dep/wire.go
  dep/wire_gen.go
  go.mod
  go.sum
  main.go
Labels: enhancement
